[package]
name = "algorithms-rs"
version = "0.1.0"
edition = "2021"
author = "davirain<davirian.yin@gmail.com>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
